#!/usr/bin/env python3

# Copyright © 2025-2026 Wenze Wei. All Rights Reserved.
#
# This file is part of DMSC.
# The DMSC project belongs to the Dunimd Team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
DMSC (Dunimd Middleware Service) - A high-performance Rust middleware framework with modular architecture.

This Python library provides bindings to the DMSC Rust core, enabling Python applications to leverage
a comprehensive set of middleware services including caching, messaging, service mesh, authentication,
device management, observability, protocol handling, and database integration. The framework follows
a plugin-based architecture where each module provides specialized functionality that can be composed
into unified middleware solutions.

Key Components:
- Core Framework: Application lifecycle management, configuration, logging, and filesystem abstraction
- Python Module Support: Native integration for Python-based service modules
- Infrastructure Services: Caching, queuing, and database connectivity
- Traffic Management: Gateway routing, rate limiting, and circuit breaker patterns
- Service Mesh: Service discovery, load balancing, and traffic routing
- Security: Authentication, authorization, and session management
- Device Management: IoT device control and resource allocation
- Observability: Metrics collection, tracing, and health monitoring
- Protocol Support: Multi-protocol connection handling and frame processing
- Data Validation: Schema validation, sanitization, and error reporting

Example Usage:
    from dmsc import DMSCAppBuilder, DMSCCacheModule, DMSCGateway
    
    app = DMSCAppBuilder("my_service").build()
    cache = DMSCCacheModule()
    gateway = DMSCGateway()
"""

__version__ = "0.1.4"
__author__ = "Dunimd Team"
__license__ = "Apache-2.0"

# Import the Rust extension module containing all DMSC bindings
# The dmsc extension is generated by PyO3 and provides zero-overhead access to Rust implementations
from .dmsc import (
    # =============================================================================
    # Core classes - Fundamental framework components for application lifecycle,
    # configuration management, logging, hooks, and service context management
    # =============================================================================
    DMSCAppBuilder, DMSCAppRuntime, DMSCConfig, DMSCConfigManager, DMSCError,
    DMSCFileSystem, DMSCHookBus, DMSCHookEvent, DMSCHookKind, DMSCLogConfig,
    DMSCLogLevel, DMSCLogger, DMSCModulePhase, DMSCServiceContext,
    
    # =============================================================================
    # Python module support - Enables Python-based service modules to integrate
    # with the DMSC framework, supporting both synchronous and asynchronous service patterns
    # =============================================================================
    DMSCPyModule, DMSCPyModuleAdapter, DMSCPyServiceModule, DMSCPyAsyncServiceModule,
    
    # =============================================================================
    # Cache classes - In-memory caching with configurable backends, eviction policies,
    # statistics tracking, and event notification capabilities
    # =============================================================================
    DMSCCacheModule, DMSCCacheManager, DMSCCacheConfig, DMSCCacheBackendType,
    DMSCCachePolicy, DMSCCacheStats, DMSCCachedValue, DMSCCacheEvent,
    
    # =============================================================================
    # Queue classes - Message queuing with multiple backend support, retry policies,
    # dead letter handling, and queue statistics monitoring
    # =============================================================================
    DMSCQueueModule, DMSCQueueConfig, DMSCQueueManager, DMSCQueueMessage, 
    DMSCQueueStats, DMSCQueueBackendType, DMSCRetryPolicy, DMSCDeadLetterConfig,
    
    # =============================================================================
    # Gateway classes - Traffic management including HTTP routing, rate limiting,
    # circuit breaker patterns, and sliding window algorithms for distributed systems
    # =============================================================================
    DMSCGateway, DMSCGatewayConfig, DMSCRouter, DMSCRoute,
    DMSCRateLimiter, DMSCRateLimitConfig, RateLimitStats,
    DMSCSlidingWindowRateLimiter, DMSCCircuitBreaker, DMSCCircuitBreakerConfig,
    DMSCCircuitBreakerState, CircuitBreakerMetrics,
    
    # =============================================================================
    # Service mesh classes - Service discovery, traffic routing, load balancing,
    # weighted destinations, and traffic splitting for microservices architecture
    # =============================================================================
    DMSCServiceMesh, DMSCServiceMeshConfig, DMSCServiceDiscovery,
    DMSCServiceInstance, DMSCServiceStatus,
    DMSCTrafficRoute, DMSCMatchCriteria, DMSCRouteAction, DMSCWeightedDestination,
    
    # =============================================================================
    # Auth classes - Authentication and authorization including JWT management,
    # session handling, OAuth integration, role-based and permission-based access control
    # =============================================================================
    DMSCAuthModule, DMSCAuthConfig, DMSCJWTManager, DMSCSessionManager,
    DMSCSecurityManager, DMSCOAuthManager, DMSCOAuthToken, DMSCOAuthUserInfo,
    DMSCPermissionManager, DMSCPermission, DMSCRole, JWTRevocationList,
    
    # =============================================================================
    # Device classes - IoT device management including device control, health monitoring,
    # resource allocation, connection pooling, and network device discovery
    # =============================================================================
    DMSCDeviceControlModule, DMSCDevice, DMSCDeviceType, DMSCDeviceStatus,
    DMSCDeviceCapabilities, DMSCDeviceHealthMetrics, DMSCDeviceController,
    DMSCDeviceConfig, DMSCDeviceControlConfig, NetworkDeviceInfo,
    DMSCDiscoveryResult, DMSCResourceRequest,
    DMSCResourceAllocation, DMSCRequestSlaClass, DMSCResourceWeights,
    DMSCAffinityRules,
    DMSCResourcePool, DMSCResourcePoolConfig, DMSCResourcePoolStatistics, DMSCResourcePoolManager,
    DMSCConnectionPoolStatistics,
    
    # =============================================================================
    # Observability classes - Metrics, tracing, and health monitoring for system
    # observability and performance analysis
    # =============================================================================
    DMSCObservabilityModule, DMSCObservabilityConfig,
    DMSCMetricsRegistry, DMSCTracer,
    DMSCMetricType, DMSCMetricConfig, DMSCMetricSample, DMSCMetric,
    DMSCObservabilityData,
    
    # =============================================================================
    # Validation classes - Data validation, schema validation, sanitization,
    # and validation result reporting with configurable severity levels
    # =============================================================================
    DMSCValidationError, DMSCValidationResult, DMSCValidationSeverity,
    DMSCValidatorBuilder, DMSCValidationRunner, DMSCSanitizer,
    DMSCSanitizationConfig, DMSCSchemaValidator, DMSCValidationModule,
    
    # =============================================================================
    # Protocol classes - Multi-protocol support including connection management,
    # frame processing, security levels, and protocol statistics monitoring
    # =============================================================================
    DMSCProtocolManager, DMSCProtocolType, DMSCProtocolConfig,
    DMSCProtocolStatus, DMSCProtocolStats, DMSCConnectionState,
    DMSCConnectionStats, DMSCProtocolHealth,
    DMSCFrame, DMSCFrameHeader, DMSCFrameType,
    DMSCConnectionInfo, DMSCMessageFlags, DMSCSecurityLevel,
    
    # =============================================================================
    # Database classes - Database configuration, connection pooling, row-level
    # access, and result set management across different database backends
    # =============================================================================
    DMSCDatabaseConfig, DMSCDatabasePool, DMSCDBRow, DMSCDBResult, DatabaseType,
)

# =============================================================================
# Submodules - Functional submodules organized by domain area, providing
# specialized functionality for specific middleware concerns
# =============================================================================
from .dmsc import (
    log, config, device, cache, fs, hooks, observability,
    queue, gateway, service_mesh, auth, protocol, database
)

# =============================================================================
# __all__ export list - Public API surface defining all symbols intended for
# external use. These symbols are imported when 'from dmsc import *' is used.
# Organized by functional category for clarity and maintainability.
# =============================================================================
__all__ = [
    # Core classes - Application framework, configuration, logging, and hooks
    'DMSCAppBuilder', 'DMSCAppRuntime', 'DMSCConfig', 'DMSCConfigManager', 'DMSCError',
    'DMSCFileSystem', 'DMSCHookBus', 'DMSCHookEvent', 'DMSCHookKind', 'DMSCLogConfig',
    'DMSCLogLevel', 'DMSCLogger', 'DMSCModulePhase', 'DMSCServiceContext',
    
    # Python module support - Python service module integration
    'DMSCPyModule', 'DMSCPyModuleAdapter', 'DMSCPyServiceModule', 'DMSCPyAsyncServiceModule',
    
    # Cache classes - Caching infrastructure and management
    'DMSCCacheModule', 'DMSCCacheManager', 'DMSCCacheConfig', 'DMSCCacheBackendType',
    'DMSCCachePolicy', 'DMSCCacheStats', 'DMSCCachedValue', 'DMSCCacheEvent',
    
    # Queue classes - Message queuing infrastructure
    'DMSCQueueModule', 'DMSCQueueConfig', 'DMSCQueueManager', 'DMSCQueueMessage', 
    'DMSCQueueStats', 'DMSCQueueBackendType', 'DMSCRetryPolicy', 'DMSCDeadLetterConfig',
    
    # Gateway classes - Traffic management and resilience patterns
    'DMSCGateway', 'DMSCGatewayConfig', 'DMSCRouter', 'DMSCRoute',
    'DMSCRateLimiter', 'DMSCRateLimitConfig', 'RateLimitStats',
    'DMSCSlidingWindowRateLimiter', 'DMSCCircuitBreaker', 'DMSCCircuitBreakerConfig',
    'DMSCCircuitBreakerState', 'CircuitBreakerMetrics',
    
    # Service mesh classes - Service discovery and traffic routing
    'DMSCServiceMesh', 'DMSCServiceMeshConfig', 'DMSCServiceDiscovery',
    'DMSCServiceInstance', 'DMSCServiceStatus',
    'DMSCTrafficRoute', 'DMSCMatchCriteria', 'DMSCRouteAction', 'DMSCWeightedDestination',
    
    # Auth classes - Authentication, authorization, and session management
    'DMSCAuthModule', 'DMSCAuthConfig', 'DMSCJWTManager', 'DMSCSessionManager', 
    'DMSCSecurityManager', 'DMSCOAuthManager', 'DMSCOAuthToken', 'DMSCOAuthUserInfo',
    'DMSCPermissionManager', 'DMSCPermission', 'DMSCRole', 'JWTRevocationList',
    
    # Device classes - IoT device control and resource management
    'DMSCDeviceControlModule', 'DMSCDevice', 'DMSCDeviceType', 'DMSCDeviceStatus',
    'DMSCDeviceCapabilities', 'DMSCDeviceHealthMetrics', 'DMSCDeviceController',
    'DMSCDeviceConfig', 'DMSCDeviceControlConfig', 'NetworkDeviceInfo',
    'DMSCDiscoveryResult', 'DMSCResourceRequest',
    'DMSCResourceAllocation', 'DMSCRequestSlaClass', 'DMSCResourceWeights',
    'DMSCAffinityRules',
    'DMSCResourcePool', 'DMSCResourcePoolConfig', 'DMSCResourcePoolStatistics', 'DMSCResourcePoolManager',
    'DMSCConnectionPoolStatistics',
    
    # Observability classes - Metrics, tracing, and health monitoring
    'DMSCObservabilityModule', 'DMSCObservabilityConfig',
    'DMSCMetricsRegistry', 'DMSCTracer',
    'DMSCMetricType', 'DMSCMetricConfig', 'DMSCMetricSample', 'DMSCMetric',
    'DMSCObservabilityData',
    
    # Validation classes - Data validation and sanitization
    'DMSCValidationError', 'DMSCValidationResult', 'DMSCValidationSeverity',
    'DMSCValidatorBuilder', 'DMSCValidationRunner', 'DMSCSanitizer',
    'DMSCSanitizationConfig', 'DMSCSchemaValidator', 'DMSCValidationModule',
    
    # Protocol classes - Protocol management and connection handling
    'DMSCProtocolManager', 'DMSCProtocolType', 'DMSCProtocolConfig',
    'DMSCProtocolStatus', 'DMSCProtocolStats', 'DMSCConnectionState',
    'DMSCConnectionStats', 'DMSCProtocolHealth',
    'DMSCFrame', 'DMSCFrameHeader', 'DMSCFrameType',
    'DMSCConnectionInfo', 'DMSCMessageFlags', 'DMSCSecurityLevel',
    
    # Database classes - Database configuration and connection pooling
    'DMSCDatabaseConfig', 'DMSCDatabasePool', 'DMSCDBRow', 'DMSCDBResult', 'DatabaseType',
    
    # Submodules - Functional submodule references
    'log', 'config', 'device', 'cache', 'fs', 'hooks', 'observability',
    'queue', 'gateway', 'service_mesh', 'auth', 'protocol', 'database'
]
