#!/usr/bin/env python3

# Copyright © 2025-2026 Wenze Wei. All Rights Reserved.
#
# This file is part of DMSC.
# The DMSC project belongs to the Dunimd Team.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
DMSC (Dunimd Middleware Service) - A high-performance Rust middleware framework with modular architecture.

This Python library provides bindings to the DMSC Rust core, enabling Python applications to leverage
a comprehensive set of middleware services including caching, messaging, service mesh, authentication,
device management, observability, protocol handling, and database integration. The framework follows
a plugin-based architecture where each module provides specialized functionality that can be composed
into unified middleware solutions.

Key Components:
- Core Framework: Application lifecycle management, configuration, logging, and filesystem abstraction
- Python Module Support: Native integration for Python-based service modules
- Infrastructure Services: Caching, queuing, and database connectivity
- Traffic Management: Gateway routing, rate limiting, and circuit breaker patterns
- Service Mesh: Service discovery, load balancing, and traffic routing
- Security: Authentication, authorization, and session management
- Device Management: IoT device control and resource allocation
- Observability: Metrics collection, tracing, and health monitoring
- Protocol Support: Multi-protocol connection handling and frame processing
- Data Validation: Schema validation, sanitization, and error reporting

Example Usage:
    from dmsc import DMSCAppBuilder, DMSCCacheModule, DMSCGateway
    
    app = (DMSCAppBuilder()
        .with_config("config.yaml")
        .with_logging(DMSCLogConfig())
        .build())
    cache = DMSCCacheModule()
    gateway = DMSCGateway()
"""

__version__ = "0.1.7"
__author__ = "Dunimd Team"
__license__ = "Apache-2.0"

# Import the Rust extension module containing all DMSC bindings
# The dmsc extension is generated by PyO3 and provides zero-overhead access to Rust implementations
from .dmsc import (
    # =============================================================================
    # Core classes - Fundamental framework components for application lifecycle,
    # configuration management, logging, hooks, and service context management
    # =============================================================================
    DMSCAppBuilder, DMSCAppRuntime, DMSCConfig, DMSCConfigManager, DMSCError,
    DMSCFileSystem, DMSCHookBus, DMSCHookEvent, DMSCHookKind, DMSCLogConfig,
    DMSCLogLevel, DMSCLogger, DMSCModulePhase, DMSCServiceContext,
    
    # =============================================================================
    # Lock utilities - Safe lock utilities for concurrent programming
    # Note: DMSCLockResult is a type alias, not a pyclass
    # =============================================================================
    DMSCLockError,
    
    # =============================================================================
    # Python module support - Enables Python-based service modules to integrate
    # with the DMSC framework, supporting both synchronous and asynchronous service patterns
    # =============================================================================
    DMSCPythonModule, DMSCPythonModuleAdapter, DMSCPythonServiceModule, DMSCPythonAsyncServiceModule,
    
    # =============================================================================
    # Health check types - Health monitoring for services and modules
    # =============================================================================
    DMSCHealthStatus, DMSCHealthCheckResult, DMSCHealthCheckConfig, DMSCHealthReport,
    
    # =============================================================================
    # Lifecycle management - Module lifecycle observation
    # =============================================================================
    DMSCLifecycleObserver,
    
    # =============================================================================
    # Cache classes - In-memory caching with configurable backends, eviction policies,
    # statistics tracking, and event notification capabilities
    # =============================================================================
    DMSCCacheModule, DMSCCacheManager, DMSCCacheConfig, DMSCCacheBackendType,
    DMSCCachePolicy, DMSCCacheStats, DMSCCachedValue, DMSCCacheEvent,
    
    # =============================================================================
    # Queue classes - Message queuing with multiple backend support, retry policies,
    # dead letter handling, and queue statistics monitoring
    # =============================================================================
    DMSCQueueModule, DMSCQueueConfig, DMSCQueueManager, DMSCQueueMessage, 
    DMSCQueueStats, DMSCQueueBackendType, DMSCRetryPolicy, DMSCDeadLetterConfig,
    
    # =============================================================================
    # Gateway classes - Traffic management including HTTP routing, rate limiting,
    # circuit breaker patterns, and sliding window algorithms for distributed systems
    # =============================================================================
    DMSCGateway, DMSCGatewayConfig, DMSCRouter, DMSCRoute,
    DMSCRateLimiter, DMSCRateLimitConfig, DMSCRateLimitStats,
    DMSCSlidingWindowRateLimiter, DMSCCircuitBreaker, DMSCCircuitBreakerConfig,
    DMSCCircuitBreakerState, DMSCCircuitBreakerMetrics,
    DMSCBackendServer, DMSCLoadBalancerServerStats,
    DMSCLoadBalancer, DMSCLoadBalancerStrategy,
    
    # =============================================================================
    # Service mesh classes - Service discovery, traffic routing, load balancing,
    # weighted destinations, and traffic splitting for microservices architecture
    # =============================================================================
    DMSCServiceMesh, DMSCServiceMeshConfig, DMSCServiceDiscovery,
    DMSCServiceInstance, DMSCServiceStatus, DMSCServiceMeshStats,
    DMSCServiceEndpoint, DMSCServiceHealthStatus,
    DMSCTrafficRoute, DMSCMatchCriteria, DMSCRouteAction, DMSCWeightedDestination,
    DMSCTrafficManager, DMSCHealthChecker, DMSCHealthSummary, DMSCHealthCheckType,
    
    # =============================================================================
    # Service Mesh classes - Advanced service management including circuit breakers,
    # health checks, and rate limiting
    # Note: DMSCCircuitBreaker, DMSCCircuitBreakerConfig, DMSCCircuitBreakerState, DMSCCircuitBreakerMetrics
    # are already imported above in the Gateway classes section
    DMSCHealthCheckConfig, DMSCHealthCheckType, DMSCHealthCheckResult,
    DMSCHealthChecker, DMSCHealthSummary,
    
    # =============================================================================
    # Auth classes - Authentication and authorization including JWT management,
    # session handling, OAuth integration, role-based and permission-based access control
    # =============================================================================
    DMSCAuthModule, DMSCAuthConfig, DMSCJWTManager, DMSCJWTClaims, DMSCJWTValidationOptions,
    DMSCSessionManager, DMSCSession, DMSCPermissionManager, DMSCPermission, DMSCRole,
    DMSCOAuthManager, DMSCOAuthToken, DMSCOAuthUserInfo, DMSCOAuthProvider,
    DMSCJWTRevocationList, DMSCRevokedTokenInfo,
    
    # =============================================================================
    # Device classes - IoT device management including device control, health monitoring,
    # resource allocation, connection pooling, and network device discovery
    # =============================================================================
    DMSCDeviceControlModule, DMSCDevice, DMSCDeviceType, DMSCDeviceStatus,
    DMSCDeviceCapabilities, DMSCDeviceHealthMetrics, DMSCDeviceController,
    DMSCDeviceConfig, DMSCDeviceControlConfig, DMSCDeviceSchedulingConfig, DMSCNetworkDeviceInfo,
    DMSCDiscoveryResult, DMSCResourceRequest,
    DMSCResourceAllocation, DMSCRequestSlaClass, DMSCResourceWeights,
    DMSCAffinityRules,
    DMSCResourcePool, DMSCResourcePoolConfig, DMSCResourcePoolStatistics, DMSCResourcePoolManager,
    DMSCResourcePoolStatus, DMSCConnectionPoolStatistics,
    DMSCResourceScheduler, DMSCDeviceScheduler, DMSCSchedulingPolicy,
    DMSCAllocationRecord, DMSCAllocationRequest, DMSCAllocationStatistics,
    DMSCDeviceTypeStatistics, DMSCSchedulingRecommendation, DMSCSchedulingRecommendationType,
    DMSCDeviceDiscoveryEngine,
    
    # =============================================================================
    # Observability classes - Metrics, tracing, and health monitoring for system
    # observability and performance analysis
    # =============================================================================
    DMSCObservabilityModule, DMSCObservabilityConfig,
    DMSCMetricsRegistry, DMSCTracer,
    DMSCMetricType, DMSCMetricConfig, DMSCMetricSample, DMSCMetric,
    DMSCObservabilityData,
    
    # =============================================================================
    # Validation classes - Data validation, schema validation, sanitization,
    # and validation result reporting with configurable severity levels
    # =============================================================================
    DMSCValidationError, DMSCValidationResult, DMSCValidationSeverity,
    DMSCValidatorBuilder, DMSCValidationRunner, DMSCSanitizer,
    DMSCSanitizationConfig, DMSCSchemaValidator, DMSCValidationModule,
    
    # =============================================================================
    # Protocol classes - Multi-protocol support including connection management,
    # frame processing, security levels, and protocol statistics monitoring
    # =============================================================================
    DMSCProtocolManager, DMSCProtocolType, DMSCProtocolConfig,
    DMSCProtocolStatus, DMSCProtocolStats, DMSCConnectionState,
    DMSCConnectionStats, DMSCProtocolHealth,
    DMSCFrame, DMSCFrameHeader, DMSCFrameType,
    DMSCConnectionInfo, DMSCMessageFlags, DMSCSecurityLevel,
    DMSCFrameParser, DMSCFrameBuilder,
    
    # =============================================================================
    # Database classes - Database configuration, connection pooling, row-level
    # access, and result set management across different database backends
    # =============================================================================
    DMSCDatabaseConfig, DMSCDatabasePool, DMSCDBRow, DMSCDBResult,
    DMSCPyORMRepository,

    # =============================================================================
    # gRPC classes - gRPC server and client support
    # =============================================================================
    DMSCGrpcConfig, DMSCGrpcStats, DMSCGrpcServiceRegistry,
    DMSCGrpcPythonService, DMSCGrpcServiceRegistryPy,
    DMSCGrpcServer, DMSCGrpcClient,

    # =============================================================================
    # WebSocket classes - WebSocket server and client support
    # =============================================================================
    DMSCWSServerConfig, DMSCWSEvent, DMSCWSSessionInfo, DMSCWSServerStats,
    DMSCWSPythonHandler, DMSCWSSessionManagerPy,
    DMSCWSServer, DMSCWSClientConfig, DMSCWSClientStats, DMSCWSClient,
)

# =============================================================================
# Submodules - Functional submodules organized by domain area, providing
# specialized functionality for specific middleware concerns
# =============================================================================
from .dmsc import (
    device, cache, fs, hooks, observability,
    queue, gateway, service_mesh, auth, protocol, database,
    grpc, ws
)

# =============================================================================
# __all__ export list - Public API surface defining all symbols intended for
# external use. These symbols are imported when 'from dmsc import *' is used.
# Organized by functional category for clarity and maintainability.
# =============================================================================
__all__ = [
    # Core classes - Application framework, configuration, logging, and hooks
    'DMSCAppBuilder', 'DMSCAppRuntime', 'DMSCConfig', 'DMSCConfigManager', 'DMSCError',
    'DMSCFileSystem', 'DMSCHookBus', 'DMSCHookEvent', 'DMSCHookKind', 'DMSCLogConfig',
    'DMSCLogLevel', 'DMSCLogger', 'DMSCModulePhase', 'DMSCServiceContext',
    
    # Lock utilities - Safe lock utilities for concurrent programming
    'DMSCLockError',
    
    # Python module support - Python service module integration
    'DMSCPythonModule', 'DMSCPythonModuleAdapter', 'DMSCPythonServiceModule', 'DMSCPythonAsyncServiceModule',
    
    # Health check types - Health monitoring for services and modules
    'DMSCHealthStatus', 'DMSCHealthCheckResult', 'DMSCHealthCheckConfig', 'DMSCHealthReport',
    
    # Lifecycle management - Module lifecycle observation
    'DMSCLifecycleObserver',
    
    # Cache classes - Caching infrastructure and management
    'DMSCCacheModule', 'DMSCCacheManager', 'DMSCCacheConfig', 'DMSCCacheBackendType',
    'DMSCCachePolicy', 'DMSCCacheStats', 'DMSCCachedValue', 'DMSCCacheEvent',
    
    # Queue classes - Message queuing infrastructure
    'DMSCQueueModule', 'DMSCQueueConfig', 'DMSCQueueManager', 'DMSCQueueMessage', 
    'DMSCQueueStats', 'DMSCQueueBackendType', 'DMSCRetryPolicy', 'DMSCDeadLetterConfig',
    
    # Gateway classes - Traffic management and resilience patterns
    'DMSCGateway', 'DMSCGatewayConfig', 'DMSCRouter', 'DMSCRoute',
    'DMSCRateLimiter', 'DMSCRateLimitConfig', 'DMSCRateLimitStats',
    'DMSCSlidingWindowRateLimiter', 'DMSCCircuitBreaker', 'DMSCCircuitBreakerConfig',
    'DMSCCircuitBreakerState', 'DMSCCircuitBreakerMetrics',
    'DMSCBackendServer', 'DMSCLoadBalancerServerStats',
    'DMSCLoadBalancer', 'DMSCLoadBalancerStrategy',
    
    # Service mesh classes - Service discovery, traffic routing, and health checking
    'DMSCServiceMesh', 'DMSCServiceMeshConfig', 'DMSCServiceDiscovery',
    'DMSCServiceInstance', 'DMSCServiceStatus', 'DMSCServiceMeshStats',
    'DMSCServiceEndpoint', 'DMSCServiceHealthStatus',
    'DMSCTrafficRoute', 'DMSCMatchCriteria', 'DMSCRouteAction', 'DMSCWeightedDestination',
    'DMSCTrafficManager', 'DMSCHealthChecker', 'DMSCHealthSummary', 'DMSCHealthCheckType',
    'DMSCHealthCheckConfig', 'DMSCHealthCheckResult',
    
    # Auth classes - Authentication, authorization, and session management
    'DMSCAuthModule', 'DMSCAuthConfig', 'DMSCJWTManager', 'DMSCJWTClaims', 'DMSCJWTValidationOptions',
    'DMSCSessionManager', 'DMSCSession', 'DMSCPermissionManager', 'DMSCPermission', 'DMSCRole',
    'DMSCOAuthManager', 'DMSCOAuthToken', 'DMSCOAuthUserInfo', 'DMSCOAuthProvider',
    'DMSCJWTRevocationList', 'DMSCRevokedTokenInfo',
    
    # Device classes - IoT device control and resource management
    'DMSCDeviceControlModule', 'DMSCDevice', 'DMSCDeviceType', 'DMSCDeviceStatus',
    'DMSCDeviceCapabilities', 'DMSCDeviceHealthMetrics', 'DMSCDeviceController',
    'DMSCDeviceConfig', 'DMSCDeviceControlConfig', 'DMSCDeviceSchedulingConfig', 'DMSCNetworkDeviceInfo',
    'DMSCDiscoveryResult', 'DMSCResourceRequest',
    'DMSCResourceAllocation', 'DMSCRequestSlaClass', 'DMSCResourceWeights',
    'DMSCAffinityRules',
    'DMSCResourcePool', 'DMSCResourcePoolConfig', 'DMSCResourcePoolStatistics', 'DMSCResourcePoolManager',
    'DMSCResourcePoolStatus', 'DMSCConnectionPoolStatistics',
    'DMSCResourceScheduler', 'DMSCDeviceScheduler', 'DMSCSchedulingPolicy',
    'DMSCAllocationRecord', 'DMSCAllocationRequest', 'DMSCAllocationStatistics',
    'DMSCDeviceTypeStatistics', 'DMSCSchedulingRecommendation', 'DMSCSchedulingRecommendationType',
    'DMSCDeviceDiscoveryEngine',
    
    # Observability classes - Metrics, tracing, and monitoring
    'DMSCObservabilityModule', 'DMSCObservabilityConfig',
    'DMSCMetricsRegistry', 'DMSCTracer',
    'DMSCMetricType', 'DMSCMetricConfig', 'DMSCMetricSample', 'DMSCMetric',
    'DMSCObservabilityData',
    
    # Validation classes - Data validation and sanitization
    'DMSCValidationError', 'DMSCValidationResult', 'DMSCValidationSeverity',
    'DMSCValidatorBuilder', 'DMSCValidationRunner', 'DMSCSanitizer',
    'DMSCSanitizationConfig', 'DMSCSchemaValidator', 'DMSCValidationModule',
    
    # Protocol classes - Multi-protocol support and frame processing
    'DMSCProtocolManager', 'DMSCProtocolType', 'DMSCProtocolConfig',
    'DMSCProtocolStatus', 'DMSCProtocolStats', 'DMSCConnectionState',
    'DMSCConnectionStats', 'DMSCProtocolHealth',
    'DMSCFrame', 'DMSCFrameHeader', 'DMSCFrameType',
    'DMSCConnectionInfo', 'DMSCMessageFlags', 'DMSCSecurityLevel',
    'DMSCFrameParser', 'DMSCFrameBuilder',

    # Database classes - Database configuration and connection pooling
    'DMSCDatabaseConfig', 'DMSCDatabasePool', 'DMSCDBRow', 'DMSCDBResult',
    'DMSCPyORMRepository',

    # gRPC classes - gRPC server and client support
    'DMSCGrpcConfig', 'DMSCGrpcStats', 'DMSCGrpcServiceRegistry',
    'DMSCGrpcPythonService', 'DMSCGrpcServiceRegistryPy',
    'DMSCGrpcServer', 'DMSCGrpcClient',

    # WebSocket classes - WebSocket server and client support
    'DMSCWSServerConfig', 'DMSCWSEvent', 'DMSCWSSessionInfo', 'DMSCWSServerStats',
    'DMSCWSPythonHandler', 'DMSCWSSessionManagerPy',
    'DMSCWSServer', 'DMSCWSClientConfig', 'DMSCWSClientStats', 'DMSCWSClient',

    # Submodules - Functional submodule references
    'device', 'cache', 'fs', 'hooks', 'observability',
    'queue', 'gateway', 'service_mesh', 'auth', 'protocol', 'database',
    'grpc', 'ws'
]


class DMSCAppBuilder:
    """Python wrapper for DMSC application builder.
    
    This class provides a Pythonic interface to the Rust DMSCAppBuilder,
    enabling configuration of DMSC applications with method chaining.
    
    Example:
        app = (DMSCAppBuilder()
            .with_config("config.yaml")
            .with_logging(DMSCLogConfig())
            .with_observability(DMSCObservabilityConfig())
            .build())
    """
    
    def __init__(self):
        from .dmsc import DMSCAppBuilder as RustBuilder
        self._builder = RustBuilder()
    
    def with_config(self, config_path: str) -> 'DMSCAppBuilder':
        """Add a configuration file path."""
        self._builder = self._builder.py_with_config(config_path)
        return self
    
    def with_logging(self, config: 'DMSCLogConfig') -> 'DMSCAppBuilder':
        """Configure logging with the provided config."""
        self._builder = self._builder.py_with_logging(config)
        return self
    
    def with_observability(self, config: 'DMSCObservabilityConfig') -> 'DMSCAppBuilder':
        """Configure observability with the provided config."""
        self._builder = self._builder.py_with_observability(config)
        return self
    
    def with_module(self, module) -> 'DMSCAppBuilder':
        """Add a module to the application."""
        self._builder = self._builder.py_with_module(module)
        return self
    
    def with_modules(self, modules: list) -> 'DMSCAppBuilder':
        """Add multiple modules to the application."""
        self._builder = self._builder.py_with_modules(modules)
        return self
    
    def with_async_module(self, module) -> 'DMSCAppBuilder':
        """Add an async module to the application."""
        self._builder = self._builder.py_with_async_module(module)
        return self
    
    def with_async_modules(self, modules: list) -> 'DMSCAppBuilder':
        """Add multiple async modules to the application."""
        self._builder = self._builder.py_with_async_modules(modules)
        return self
    
    def with_python_module(self, module) -> 'DMSCAppBuilder':
        """Add a Python module to the application."""
        self._builder = self._builder.py_with_python_module(module)
        return self
    
    def with_dms_module(self, module) -> 'DMSCAppBuilder':
        """Add a DMSC module to the application."""
        self._builder = self._builder.py_with_dms_module(module)
        return self
    
    def with_dms_modules(self, modules: list) -> 'DMSCAppBuilder':
        """Add multiple DMSC modules to the application."""
        self._builder = self._builder.py_with_dms_modules(modules)
        return self
    
    def build(self) -> 'DMSCAppRuntime':
        """Build the application runtime."""
        return self._builder.py_build()
